apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mcapi
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: mcapi
    spec:
      imagePullSecrets:
        - name: acr-openhacktable11
      containers:
      - name: mcapi
        image: openhacktable11.azurecr.io/openhacktable11:0.17
        ports:
        - name: mcapi
          containerPort: 5002
          protocol: TCP
